spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: josieyan123@gmail.com
    password: uvxhgfsogbplswyi
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
