server:
  port: 8081 #端口号
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 476865287@qq.com
    password: jvyqbkmwvikgcaji
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          auth: true
    protocol: smtp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
