server:
  port: 8081 #端口号
spring:
  mail:
    host: smtp.qq.com
    version: xxxxx
    port: 465
    username: 476865287@qq.com
    password: jvyqbkmwvikgcaji
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          auth: true
    protocol: smtp
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${server.port}
