server:
  port: 9006
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XIDP-yanzemin/config.git
          username: josieyan123
          password: YANZemin123
          search-paths: config
        default-label: main
      discovery:
        enabled: true
        service-id: ${spring.application.name}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
