server:
  port: 9006
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XIDP-yanzemin/spring-cloud-config-server.git #????????
          search-paths: config
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
